@@ .. @@
-import { ThemeProvider } from './components/ThemeProvider'
-import Navigation from './components/Navigation'
-import BubbleBackground from './components/BubbleBackground'
-import HeroSection from './components/sections/HeroSection'
-import AboutSection from './components/sections/AboutSection'
-import ProjectsSection from './components/sections/ProjectsSection'
-import ExperienceSection from './components/sections/ExperienceSection'
-import SkillsSection from './components/sections/SkillsSection'
-import TestimonialsSection from './components/sections/TestimonialsSection'
-import AchievementsSection from './components/sections/AchievementsSection'
-import CertificationsSection from './components/sections/CertificationsSection'
-import ContactSection from './components/sections/ContactSection'
-import { Toaster } from './components/ui/sonner'
+import { ThemeProvider } from '@/components/ThemeProvider'
+import Navigation from '@/components/Navigation'
+import BubbleBackground from '@/components/BubbleBackground'
+import HeroSection from '@/components/sections/HeroSection'
+import AboutSection from '@/components/sections/AboutSection'
+import ProjectsSection from '@/components/sections/ProjectsSection'
+import ExperienceSection from '@/components/sections/ExperienceSection'
+import SkillsSection from '@/components/sections/SkillsSection'
+import TestimonialsSection from '@/components/sections/TestimonialsSection'
+import AchievementsSection from '@/components/sections/AchievementsSection'
+import CertificationsSection from '@/components/sections/CertificationsSection'
+import ContactSection from '@/components/sections/ContactSection'
+import { Toaster } from '@/components/ui/sonner'